exec-y += samscsdk

samscsdk-cflags-y := -DAPPCONFIG_DEBUG_ENABLE -DCRYPTO_ATMEL -DMARVELL_88MW302 -DATCA_HAL_I2C -D__TINY__ -DAES_STANDALONE -DWOLFSSL_KEY_GEN -I$(d)/src -I$(d)/ext_libs/mbedtls/include -I$(d)/ext_libs/atmel -I$(d)/include
samscsdk-objs-y := \
		src/main.c \
		src/https.c \
		src/samscsdk.c \
		src/set_device_time.c \
		src/crypto/crypto_atmel.c \
		src/crypto/crypto_tiny_atmel.c \
		src/crypto/atecc508a/data.c \
		src/crypto/atecc508a/provision.c \
		src/crypto/converters/converters_tiny.c \
		src/crypto/converters/converters.c \
		src/crypto/asn1/asn1.c \
		src/crypto/aes/aes.c \
		src/crypto/hal/mw300_i2c_hal.c \
		ext_libs/atmel/atcacert/atcacert_client.c \
		ext_libs/atmel/atcacert/atcacert_date.c \
		ext_libs/atmel/atcacert/atcacert_def.c \
		ext_libs/atmel/atcacert/atcacert_der.c \
		ext_libs/atmel/atcacert/atcacert_host_hw.c \
		ext_libs/atmel/basic/atca_basic.c \
		ext_libs/atmel/basic/atca_helpers.c \
		ext_libs/atmel/crypto/hashes/sha1_routines.c \
		ext_libs/atmel/crypto/hashes/sha2_routines.c \
		ext_libs/atmel/crypto/atca_crypto_sw_ecdsa.c \
		ext_libs/atmel/crypto/atca_crypto_sw_rand.c \
		ext_libs/atmel/crypto/atca_crypto_sw_sha1.c \
		ext_libs/atmel/crypto/atca_crypto_sw_sha2.c \
		ext_libs/atmel/hal/atca_hal.c \
		ext_libs/atmel/host/atca_host.c \
		ext_libs/atmel/tls/atcatls.c \
		ext_libs/atmel/atca_cfgs.c \
		ext_libs/atmel/atca_command.c \
		ext_libs/atmel/atca_device.c \
		ext_libs/atmel/atca_iface.c \
#		ext_libs/mbedtls/library/aes.c \
		ext_libs/mbedtls/library/aesni.c \
		ext_libs/mbedtls/library/arc4.c \
		ext_libs/mbedtls/library/asn1parse.c \
		ext_libs/mbedtls/library/asn1write.c \
		ext_libs/mbedtls/library/base64.c \
		ext_libs/mbedtls/library/bignum.c \
		ext_libs/mbedtls/library/blowfish.c \
		ext_libs/mbedtls/library/camellia.c \
		ext_libs/mbedtls/library/ccm.c \
		ext_libs/mbedtls/library/cipher.c \
		ext_libs/mbedtls/library/cipher_wrap.c \
		ext_libs/mbedtls/library/cmac.c \
		ext_libs/mbedtls/library/ctr_drbg.c \
		ext_libs/mbedtls/library/des.c \
		ext_libs/mbedtls/library/dhm.c \
 		ext_libs/mbedtls/library/ecdh.c \
		ext_libs/mbedtls/library/ecdsa.c \
		ext_libs/mbedtls/library/ecjpake.c \
		ext_libs/mbedtls/library/ecp.c \
		ext_libs/mbedtls/library/ecp_curves.c \
		ext_libs/mbedtls/library/entropy.c \
		ext_libs/mbedtls/library/entropy_poll.c \
		ext_libs/mbedtls/library/error.c \
		ext_libs/mbedtls/library/gcm.c \
		ext_libs/mbedtls/library/havege.c \
		ext_libs/mbedtls/library/hmac_drbg.c \
		ext_libs/mbedtls/library/md.c \
		ext_libs/mbedtls/library/md2.c \
		ext_libs/mbedtls/library/md4.c \
		ext_libs/mbedtls/library/md5.c \
		ext_libs/mbedtls/library/md_wrap.c \
		ext_libs/mbedtls/library/memory_buffer_alloc.c \
		ext_libs/mbedtls/library/oid.c \
		ext_libs/mbedtls/library/padlock.c \
		ext_libs/mbedtls/library/pem.c \
		ext_libs/mbedtls/library/pk.c \
		ext_libs/mbedtls/library/pk_wrap.c \
		ext_libs/mbedtls/library/pkcs12.c \
		ext_libs/mbedtls/library/pkcs5.c \
		ext_libs/mbedtls/library/pkparse.c \
		ext_libs/mbedtls/library/pkwrite.c \
		ext_libs/mbedtls/library/platform.c \
		ext_libs/mbedtls/library/ripemd160.c \
		ext_libs/mbedtls/library/rsa.c \
		ext_libs/mbedtls/library/sha1.c \
		ext_libs/mbedtls/library/sha256.c \
		ext_libs/mbedtls/library/sha512.c \
		ext_libs/mbedtls/library/timing.c \
		ext_libs/mbedtls/library/threading.c \
		ext_libs/mbedtls/library/version.c \
		ext_libs/mbedtls/library/version_features.c \
		ext_libs/mbedtls/library/xtea.c \
		